### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ilyar** [tadatuta/bb#9]
Попробовал собрать проект, свалился.

Еще не разобрался, предположу, что некоторые места надо актуализировать. 

@tadatuta уточни в каком направлении посмотреть актуализацию, чтобы я сильно в сторону не ушел, разбираясь со сборкой?

```bash
npm start

> bem-blog@1.0.0 start /space/projects/Dokerware/Dokerware/tmp/bb
> npm run build && bem server


> bem-blog@1.0.0 build /space/projects/Dokerware/Dokerware/tmp/bb
> enb make && node grab.js && node generate.js && cp desktop.bundles/index/index.min.css output/ && cp desktop.bundles/index/index.min.js output/

14:57:48.024 - build started
14:57:48.065 - [rebuild] [desktop.bundles/index/index.bemdecl.js] file-provider
14:57:48.181 - [rebuild] [desktop.bundles/index/index.levels] levels
14:57:48.186 - [isValid] [desktop.bundles/index/index.deps.js] deps
14:57:48.202 - [rebuild] [desktop.bundles/index/index.files] files
14:57:48.202 - [rebuild] [desktop.bundles/index/index.dirs] files
14:57:48.205 - [isValid] [desktop.bundles/index/index.bemhtml.bemdecl.js] deps-by-tech-to-bemdecl
14:57:48.206 - [isValid] [desktop.bundles/index/index.bemtree.js] bemtree
14:57:48.206 - [isValid] [desktop.bundles/index/index.css] stylus
14:57:48.207 - [isValid] [desktop.bundles/index/index.browser.js] browser-js
14:57:48.209 - [isValid] [desktop.bundles/index/index.bemhtml.deps.js] deps
14:57:48.218 - [isValid] [desktop.bundles/index/index.min.css] borschik
14:57:48.218 - [rebuild] [desktop.bundles/index/index.bemhtml.files] files
14:57:48.218 - [rebuild] [desktop.bundles/index/index.bemhtml.dirs] files
14:57:48.218 - [isValid] [desktop.bundles/index/index.browser.bemhtml.js] bemhtml
14:57:48.219 - [isValid] [desktop.bundles/index/index.js] file-merge
14:57:48.219 - [isValid] [desktop.bundles/index/index.min.js] borschik
14:57:48.220 - build finished - 1163ms
module.js:471
    throw err;
    ^

Error: Cannot find module './desktop.bundles/index/index.bemhtml.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/space/projects/Dokerware/Dokerware/tmp/bb/generate.js:4:66)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bem-blog@1.0.0 build: `enb make && node grab.js && node generate.js && cp desktop.bundles/index/index.min.css output/ && cp desktop.bundles/index/index.min.js output/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bem-blog@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ilyar/.npm/_logs/2017-08-19T11_57_48_751Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bem-blog@1.0.0 start: `npm run build && bem server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bem-blog@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ilyar/.npm/_logs/2017-08-19T11_57_48_772Z-debug.log
```

**Comment by ilyar** [comment]
> Антон Виноградов когда-то форкнул bb и сделал https://github.com/theprotein/mad-mark
